### ISSUE TITLE
Find does not match substring for feed times

### ISSUE THREAD

**Issue by aizatazhar** [AY2021S1-CS2103T-W15-4/tp#273]
In #269, `find` now matches by substring, but it doesn't seem to work for when finding feed times. For example `find 120` should display Hashbrown since it has a feed time of `1200`.

Also `StringUtil#containsWordIgnoreCase`'s javadocs needs to be updated to reflect that it finds by substring now

**Comment by lamlaaaam** [comment]
From a use case perspective, I think feed times should not be matched by substring. Suggest updating UG to specify substring matching for strings and full match for integers?

**Comment by m0nggh** [comment]
Agreed that feed time should probably be matched entirely for a hit. However, I'm not sure if it is strange that id can be matched by substring since finding '1' can find like many animals.

**Comment by aizatazhar** [comment]
Agree with both, maybe can just specify if finding by ID or feed times we need an exact match, the rest of the fields is partial. But then there can be weird case where if i named my animal by a number e.g. name: 12345 and did `find 123` it would display this animal.

Personally i would prefer having exact match for every field for consistency. I thought all the issues raised was just documentation related, i.e. it was unclear what `find` does exactly.

An alternative solution would be to have find take in another parameter which is the field to search. e.g. `find n/Hashbrown` and `find i/123`? It is more intuitive but at this stage idk if anyone would want to implement this because prone to bugs + update tests + update documentation

**Comment by JunCheng98** [comment]
I made the find command match substrings since I think it could possibly be labelled a feature flaw if substring matching was not supported. 

It also makes the command more flexible anyway which I think is a plus and could make it less of a hassle if users want to search for a general type of animal i.e. bird or fish instead of looking for a specific species. I can allow for substring matching for feed times quite easily if it's fine with you all since it was a minor error that stemmed from my previous implementation of find.
